# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_Yxgxe0TcZW2rCUqqA3ScGNWzmtugZD
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 5, 6])
y = np.array([0, 25, 250])

plt.plot(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([0, 5, 8, 9])

plt.plot(y, marker="o")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([0, 5, 8, 9])

plt.plot(y, 'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([0, 5, 8, 9])

plt.plot(y, marker="o", ms=20, mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([0, 5, 8, 9])

plt.plot(y, marker="o", ms='20', mfc='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([0, 1, 5, 6, 8])
y1 = np.array([3, 8, 1, 9, 12])
x2 = np.array([5, 8, 9, 11, 4])
y2 = np.array([7, 1, 5, 5, 9])

plt.plot(x1, y1, x2, y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([0, 5, 8, 9])

plt.plot(y, marker="o", ms='20', mfc='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([0, 5, 8, 9])
x = np.array([2, 6, 9, 11])
plt.scatter(x, y,color='red')
y = np.array([5, 8, 9, 11])
x = np.array([3, 6, 7, 5])
plt.scatter(x, y,color='green')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 2, 3, 5])
y = np.array([0, 25, 26, 28])

plt.scatter(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 2, 26, 28, 30, 32])
mycolor=['red','green','blue', 'lime', 'aqua','yellow']

plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 2, 26, 28, 30, 32])
mycolor=['red','green','blue', 'lime', 'aqua','yellow']
size=[100, 200,300,400,500,600]

plt.scatter(x,y,color=mycolor, s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 2, 26, 28, 30, 32])
mycolor=['red','green','blue', 'lime', 'aqua','yellow']

plt.scatter(x,y,color=mycolor, s=size, alpha=0.3)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['614-23', '613-23', '510-23'])
y = np.array([23, 22, 18])

plt.bar(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['614-23', '613-23', '510-23'])
y = np.array([23, 22, 18])

plt.barh(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 5, 8, 9])

plt.pie(y)
plt.show()